/**
 * Compute Shader RGC Integration Tests
 *
 * Tests the compute shader generation pipeline used by the EXR viewer.
 * This verifies that RGC (Reference Gamut Compression) works correctly
 * in the viewer context, both with and without DCTL.
 *
 * Run with: npm run test:vscode
 */

import * as assert from 'assert';
import * as path from 'path';
import * as fs from 'fs';
import * as vscode from 'vscode';
import { getTestOutputDir } from '@dctl-workbench/core/out/test-paths.js';

const TEST_DCTL_GAIN = `
// Simple gain DCTL for testing
DEFINE_UI_PARAMS(gain, Gain, DCTLUI_SLIDER_FLOAT, 2.0, 0.0, 4.0, 0.01)

__DEVICE__ float3 transform(int p_Width, int p_Height, int p_X, int p_Y, float p_R, float p_G, float p_B)
{
    float3 rgb = make_float3(p_R, p_G, p_B);
    return rgb * gain;
}
`;

const TEST_DCTL_TEX2D = `
// Texture-based DCTL for testing
DEFINE_UI_PARAMS(gain, Gain, DCTLUI_SLIDER_FLOAT, 2.0, 0.0, 4.0, 0.01)

__DEVICE__ float3 transform(int p_Width, int p_Height, int p_X, int p_Y, __TEXTURE__ p_TexR, __TEXTURE__ p_TexG, __TEXTURE__ p_TexB)
{
    float r = _tex2D(p_TexR, p_X, p_Y);
    float g = _tex2D(p_TexG, p_X, p_Y);
    float b = _tex2D(p_TexB, p_X, p_Y);
    return make_float3(r * gain, g * gain, b * gain);
}
`;

suite('Compute Shader RGC Integration Tests', () => {
    let extensionPath: string;

    suiteSetup(async function() {
        this.timeout(30000);

        // Get extension path from vscode
        const extension = vscode.extensions.getExtension('your-publisher-id.dctl-workbench');
        if (extension) {
            extensionPath = extension.extensionPath;
        } else {
            // Fallback: calculate from __dirname
            if (__dirname.includes('/out/')) {
                extensionPath = path.resolve(__dirname, '../../../..');
            } else {
                extensionPath = path.resolve(__dirname, '../../..');
            }
        }

        console.log('\n=== Compute Shader RGC Integration Tests ===');
        console.log('Extension path:', extensionPath);

        // Verify extension is built
        const outDir = path.join(extensionPath, 'out');
        if (!fs.existsSync(outDir)) {
            console.log('Extension not built - run npm run compile first');
            this.skip();
        }
    });

    test('Should have required shader builder modules', async function() {
        this.timeout(10000);

        const modules = [
            'out/shader/index.js',
            'out/wasm/dctl-compiler/dctl_compiler.js',
        ];

        for (const mod of modules) {
            const modulePath = path.join(extensionPath, mod);
            const exists = fs.existsSync(modulePath);
            console.log(`${mod}: ${exists ? 'OK' : 'MISSING'}`);
            assert.ok(exists, `Module ${mod} should exist`);
        }
    });

    test('Should build DCTL-only compute shader', async function() {
        this.timeout(60000);

        try {
            const shaderModule = require(path.join(extensionPath, 'out/shader/index.js'));
            const { buildIntegratedShader, buildDctlComputeShader } = shaderModule;

            assert.ok(buildIntegratedShader, 'buildIntegratedShader should be available');
            assert.ok(buildDctlComputeShader, 'buildDctlComputeShader should be available');

            console.log('\nBuilding DCTL-only compute shader...');
            console.log('DCTL source:', TEST_DCTL_GAIN.substring(0, 100) + '...');

            // Note: This test documents what SHOULD work, but may fail due to
            // OCIO WASM not being initialized in test environment
        } catch (e: any) {
            console.log('Error importing shader module:', e.message);
            if (e.code === 'MODULE_NOT_FOUND') {
                console.log('Module not found - extension may need to be built');
                this.skip();
            }
            throw e;
        }
    });

    test('Should verify DCTL compute shader has correct structure', async function() {
        this.timeout(30000);

        // Read the webview compute shader debug file (generated by the earlier test)
        // Note: webview_compute_shader_rgc.wgsl contains the full compute shader
        // compute_shader_debug.wgsl only contains DCTL functions (no entry point)
        const testResultsDir = getTestOutputDir();
        const possiblePaths = [
            path.join(testResultsDir, 'webview_compute_shader_rgc.wgsl'),
            path.join(testResultsDir, 'compute_shader_debug.wgsl'),
        ];

        let shaderCode: string | null = null;
        let foundPath = '';

        for (const p of possiblePaths) {
            if (fs.existsSync(p)) {
                shaderCode = fs.readFileSync(p, 'utf-8');
                foundPath = p;
                break;
            }
        }

        if (!shaderCode) {
            console.log('Compute shader debug file not found');
            console.log('Expected at:', possiblePaths[0]);
            console.log('Run webview RGC tests first to generate this file');
            this.skip();
            return;
        }

        console.log(`\nUsing compute shader from: ${path.basename(foundPath)}`);
        console.log(`Compute shader debug file: ${shaderCode.length} chars`);

        const checks = {
            // Use [\s\S]* to match across newlines (. doesn't match newlines)
            hasComputeEntry: /@compute[\s\S]*?fn\s+main/.test(shaderCode),
            hasWorkgroupSize: /@workgroup_size/.test(shaderCode),
            hasStorageBuffer: /var<storage/.test(shaderCode) || /texture_storage_2d/.test(shaderCode),
            hasUniformBuffer: /var<uniform>/.test(shaderCode) || /var<private>/.test(shaderCode),
        };

        console.log('\nCompute shader structure:');
        for (const [name, passed] of Object.entries(checks)) {
            console.log(`  ${name}: ${passed ? '✓' : '✗'}`);
        }

        // These are basic requirements for any compute shader
        assert.ok(checks.hasComputeEntry, 'Should have @compute entry point');
        assert.ok(checks.hasWorkgroupSize, 'Should have workgroup_size');
    });

    test('Should verify RGC compute shader has applyACES2RGC', async function() {
        this.timeout(30000);

        // Look for an RGC compute shader debug file
        const testResultsDir = getTestOutputDir();
        const possiblePaths = [
            path.join(testResultsDir, 'compute_shader_rgc_debug.wgsl'),
            path.join(testResultsDir, 'export_shader_rgc_debug.wgsl'),
        ];

        let shaderCode: string | null = null;
        let foundPath = '';

        for (const p of possiblePaths) {
            if (fs.existsSync(p)) {
                shaderCode = fs.readFileSync(p, 'utf-8');
                foundPath = p;
                break;
            }
        }

        if (!shaderCode) {
            console.log('No RGC shader debug file found');
            console.log('Checked:', possiblePaths.join(', '));
            this.skip();
            return;
        }

        console.log(`\nUsing RGC shader from: ${foundPath}`);
        console.log(`Shader length: ${shaderCode.length} chars`);

        const checks = {
            hasApplyRGC: /fn\s+applyACES2RGC/.test(shaderCode),
            hasRgcOcioFunctions: /rgc_ocio_/.test(shaderCode),
            hasRgcTextures: /rgc_.*_tex|rgc_.*Sampler_tex/.test(shaderCode),
            hasHuesArray: /hues_array/.test(shaderCode),
            hasTransform: /fn\s+transform/.test(shaderCode),
            hasSampleTexture: /fn\s+dctl_sampleTexture/.test(shaderCode),
            sampleTextureCallsRgc: /dctl_sampleTexture[\s\S]*?applyACES2RGC/.test(shaderCode),
        };

        console.log('\nRGC shader validation:');
        for (const [name, passed] of Object.entries(checks)) {
            console.log(`  ${name}: ${passed ? '✓' : '✗'}`);
        }

        // Critical checks
        assert.ok(checks.hasApplyRGC, 'RGC shader MUST have applyACES2RGC function');
        assert.ok(checks.hasRgcOcioFunctions, 'RGC shader should have rgc_ocio_ helper functions');
        assert.ok(checks.hasRgcTextures, 'RGC shader should have RGC texture bindings');
    });

    test('Should verify dctl_sampleTexture applies RGC when enabled', async function() {
        this.timeout(30000);

        const testResultsDir = getTestOutputDir();
        const rgcPath = path.join(testResultsDir, 'export_shader_rgc_debug.wgsl');

        if (!fs.existsSync(rgcPath)) {
            console.log('RGC export shader not found - run export with RGC enabled first');
            this.skip();
            return;
        }

        const shaderCode = fs.readFileSync(rgcPath, 'utf-8');

        // Extract dctl_sampleTexture function
        const sampleTextureMatch = shaderCode.match(
            /fn dctl_sampleTexture\s*\([^)]*\)\s*->\s*vec4<f32>\s*\{[\s\S]*?\n\}/
        );

        if (!sampleTextureMatch) {
            console.log('dctl_sampleTexture function not found in shader');
            assert.fail('dctl_sampleTexture should exist in RGC shader');
            return;
        }

        const sampleTextureCode = sampleTextureMatch[0];
        console.log('\ndctl_sampleTexture function:');
        console.log(sampleTextureCode.substring(0, 400) + '...');

        // Verify it calls applyACES2RGC
        const callsRgc = /applyACES2RGC\s*\(/.test(sampleTextureCode);
        console.log(`\nCalls applyACES2RGC: ${callsRgc ? '✓' : '✗'}`);

        assert.ok(callsRgc, 'dctl_sampleTexture MUST call applyACES2RGC in RGC path');

        // Verify the call is correct (ap1 = applyACES2RGC(vec4<f32>(ap1, 1.0)).rgb)
        const correctPattern = /ap1\s*=\s*applyACES2RGC\s*\(\s*vec4<f32>\s*\(\s*ap1/.test(sampleTextureCode);
        console.log(`Correct pattern: ${correctPattern ? '✓' : '✗'}`);

        assert.ok(correctPattern, 'applyACES2RGC should be called with correct arguments');
    });

    test('Should verify no duplicate entry points', async function() {
        this.timeout(30000);

        const testResultsDir = getTestOutputDir();

        const files = ['export_shader_rgc_debug.wgsl', 'export_shader_debug.wgsl'];

        for (const file of files) {
            const filePath = path.join(testResultsDir, file);
            if (!fs.existsSync(filePath)) continue;

            const shaderCode = fs.readFileSync(filePath, 'utf-8');

            // Count @fragment fn main
            const fragmentMatches = shaderCode.match(/@fragment\s*\n?\s*fn\s+main/g);
            const fragmentCount = fragmentMatches ? fragmentMatches.length : 0;

            // Count @compute fn main
            const computeMatches = shaderCode.match(/@compute\s*.*\n?\s*fn\s+main/g);
            const computeCount = computeMatches ? computeMatches.length : 0;

            console.log(`\n${file}:`);
            console.log(`  @fragment fn main: ${fragmentCount}`);
            console.log(`  @compute fn main: ${computeCount}`);

            if (fragmentCount > 0) {
                assert.strictEqual(fragmentCount, 1,
                    `${file}: Should have exactly 1 @fragment fn main, found ${fragmentCount}`);
            }

            if (computeCount > 0) {
                assert.strictEqual(computeCount, 1,
                    `${file}: Should have exactly 1 @compute fn main, found ${computeCount}`);
            }
        }
    });

    test('Should compare RGC vs non-RGC shader sizes', async function() {
        this.timeout(10000);

        const testResultsDir = getTestOutputDir();
        const rgcPath = path.join(testResultsDir, 'export_shader_rgc_debug.wgsl');
        const nonRgcPath = path.join(testResultsDir, 'export_shader_debug.wgsl');

        const results: { name: string; exists: boolean; size: number; hasRgc: boolean }[] = [];

        if (fs.existsSync(nonRgcPath)) {
            const code = fs.readFileSync(nonRgcPath, 'utf-8');
            results.push({
                name: 'Non-RGC',
                exists: true,
                size: code.length,
                hasRgc: /applyACES2RGC/.test(code),
            });
        }

        if (fs.existsSync(rgcPath)) {
            const code = fs.readFileSync(rgcPath, 'utf-8');
            results.push({
                name: 'RGC',
                exists: true,
                size: code.length,
                hasRgc: /applyACES2RGC/.test(code),
            });
        }

        if (results.length === 0) {
            console.log('No shader debug files found');
            this.skip();
            return;
        }

        console.log('\n=== Shader Comparison ===');
        console.log('Shader   | Size     | Has RGC');
        console.log('-'.repeat(35));

        for (const r of results) {
            console.log(`${r.name.padEnd(8)} | ${r.size.toString().padStart(8)} | ${r.hasRgc ? 'Yes' : 'No'}`);
        }

        // Verify RGC shader is larger (should include RGC functions)
        const nonRgc = results.find(r => r.name === 'Non-RGC');
        const rgc = results.find(r => r.name === 'RGC');

        if (nonRgc && rgc) {
            console.log(`\nSize difference: ${rgc.size - nonRgc.size} chars`);

            // RGC shader should be significantly larger
            assert.ok(rgc.size > nonRgc.size + 1000,
                'RGC shader should be at least 1000 chars larger than non-RGC');

            // RGC shader should have RGC functions
            assert.ok(rgc.hasRgc, 'RGC shader should have applyACES2RGC function');

            // Non-RGC shader should NOT have RGC functions
            assert.ok(!nonRgc.hasRgc, 'Non-RGC shader should NOT have applyACES2RGC function');
        }
    });
});
