async function OpenEXR(moduleArg={}){var moduleRtn;var d=moduleArg,p=!!globalThis.WorkerGlobalScope,aa=import.meta.url,q="",r,t;if(globalThis.window||p){try{q=(new URL(".",aa)).href}catch{}p&&(t=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});r=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var v=console.log.bind(console),w=console.error.bind(console),y,z=!1,A,B,C,D,E,F,G,H,I,J,K=!1;
function L(){var a=M.buffer;C=new Int8Array(a);E=new Int16Array(a);d.HEAPU8=D=new Uint8Array(a);new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);d.HEAPF32=H=new Float32Array(a);I=new Float64Array(a);J=new BigInt64Array(a);new BigUint64Array(a)}function N(a){d.onAbort?.(a);a="Aborted("+a+")";w(a);z=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");B?.(a);throw a;}var O;
async function ba(a){if(!y)try{var c=await r(a);return new Uint8Array(c)}catch{}if(a==O&&y)a=new Uint8Array(y);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,c){try{var b=await ba(a);return await WebAssembly.instantiate(b,c)}catch(e){w(`failed to asynchronously prepare wasm: ${e}`),N(e)}}
async function da(a){var c=O;if(!y)try{var b=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,a)}catch(e){w(`wasm streaming compile failed: ${e}`),w("falling back to ArrayBuffer instantiation")}return ca(c,a)}
var P=a=>{for(;0<a.length;)a.shift()(d)},Q=[],R=[],ea=()=>{var a=d.preRun.shift();R.push(a)},S=globalThis.TextDecoder&&new TextDecoder,T=(a,c=0,b,e)=>{var f=c;b=f+b;if(e)e=b;else{for(;a[f]&&!(f>=b);)++f;e=f}if(16<e-c&&a.buffer&&S)return S.decode(a.subarray(c,e));for(f="";c<e;)if(b=a[c++],b&128){var h=a[c++]&63;if(192==(b&224))f+=String.fromCharCode((b&31)<<6|h);else{var g=a[c++]&63;b=224==(b&240)?(b&15)<<12|h<<6|g:(b&7)<<18|h<<12|g<<6|a[c++]&63;65536>b?f+=String.fromCharCode(b):(b-=65536,f+=String.fromCharCode(55296|
b>>10,56320|b&1023))}}else f+=String.fromCharCode(b);return f},fa=[null,[],[]],U=(a,c,b)=>{var e=D;if(!(0<b))return 0;var f=c;b=c+b-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(c>=b)break;e[c++]=g}else if(2047>=g){if(c+1>=b)break;e[c++]=192|g>>6;e[c++]=128|g&63}else if(65535>=g){if(c+2>=b)break;e[c++]=224|g>>12;e[c++]=128|g>>6&63;e[c++]=128|g&63}else{if(c+3>=b)break;e[c++]=240|g>>18;e[c++]=128|g>>12&63;e[c++]=128|g>>6&63;e[c++]=128|g&63;h++}}e[c]=0;return c-f},Y=(a,c,b,e)=>{var f=
{string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){for(var m=l=0;m<k.length;++m){var x=k.charCodeAt(m);127>=x?l++:2047>=x?l+=2:55296<=x&&57343>=x?(l+=4,++m):l+=3}l+=1;m=V(l);U(k,m,l);l=m}return l},array:k=>{var l=V(k.length);C.set(k,l);return l}};a=d["_"+a];var h=[],g=0;if(e)for(var n=0;n<e.length;n++){var u=f[b[n]];u?(0===g&&(g=W()),h[n]=u(e[n])):h[n]=e[n]}b=a(...h);return b=function(k){0!==g&&X(g);return"string"===c?k?T(D,k):"":"boolean"===c?!!k:k}(b)};d.print&&(v=d.print);d.printErr&&(w=d.printErr);
d.wasmBinary&&(y=d.wasmBinary);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();d.ccall=Y;d.cwrap=(a,c,b,e)=>{var f=!b||b.every(h=>"number"===h||"boolean"===h);return"string"!==c&&f&&!e?d["_"+a]:(...h)=>Y(a,c,b,h,e)};
d.setValue=function(a,c,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":C[a]=c;break;case "i8":C[a]=c;break;case "i16":E[a>>1]=c;break;case "i32":F[a>>2]=c;break;case "i64":J[a>>3]=BigInt(c);break;case "float":H[a>>2]=c;break;case "double":I[a>>3]=c;break;case "*":G[a>>2]=c;break;default:N(`invalid type for setValue: ${b}`)}};
d.getValue=function(a,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":return C[a];case "i8":return C[a];case "i16":return E[a>>1];case "i32":return F[a>>2];case "i64":return J[a>>3];case "float":return H[a>>2];case "double":return I[a>>3];case "*":return G[a>>2];default:N(`invalid type for getValue: ${c}`)}};d.UTF8ToString=(a,c,b)=>a?T(D,a,c,b):"";d.stringToUTF8=(a,c,b)=>U(a,c,b);
var X,V,W,M,ha={k:()=>{},i:()=>{},h:function(){},e:()=>{},c:()=>{},j:a=>{var c=D.length;a>>>=0;if(2147483648<a)return!1;for(var b=1;4>=b;b*=2){var e=c*(1+.2/b);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-M.buffer.byteLength+65535)/65536|0;try{M.grow(e);L();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},b:()=>52,g:function(){return 52},f:function(){return 52},d:function(){return 70},a:(a,c,b,e)=>{for(var f=0,h=0;h<b;h++){var g=G[c>>2],n=G[c+
4>>2];c+=8;for(var u=0;u<n;u++){var k=a,l=D[g+u],m=fa[k];0===l||10===l?((1===k?v:w)(T(m)),m.length=0):m.push(l)}f+=n}G[e>>2]=f;return 0}},Z;
Z=await (async function(){function a(b){b=Z=b.exports;d._exr_wasm_init=b.n;d._exr_wasm_version=b.o;d._exr_wasm_create_write_context=b.p;d._malloc=b.q;d._free=b.r;d._exr_wasm_add_channel=b.s;d._exr_wasm_set_compression=b.t;d._exr_wasm_set_chromaticities=b.u;d._exr_wasm_set_adopt_neutral=b.v;d._exr_wasm_write_pixels=b.w;d._exr_wasm_write_interleaved=b.x;d._exr_wasm_finalize=b.y;d._exr_wasm_get_output_ptr=b.z;d._exr_wasm_get_output_size=b.A;d._exr_wasm_destroy_context=b.B;d._exr_wasm_create_read_context=
b.C;d._exr_wasm_get_dimensions=b.D;d._exr_wasm_get_channel_count=b.E;d._exr_wasm_get_channel_name=b.F;d._exr_wasm_get_channel_pixel_type=b.G;d._exr_wasm_get_compression=b.H;d._exr_wasm_read_pixels=b.I;d._exr_wasm_get_chromaticities=b.J;d._exr_wasm_get_last_error=b.K;d._exr_wasm_clear_error=b.L;d._exr_wasm_get_memory_stats=b.M;X=b.N;V=b.O;W=b.P;M=b.l;L();return Z}var c={a:ha};if(d.instantiateWasm)return new Promise(b=>{d.instantiateWasm(c,(e,f)=>{b(a(e,f))})});O??=d.locateFile?d.locateFile?d.locateFile("openexr.wasm",
q):q+"openexr.wasm":(new URL("openexr.wasm",import.meta.url)).href;return a((await da(c)).instance)}());
(function(){function a(){d.calledRun=!0;if(!z){K=!0;Z.m();A?.(d);d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var c=d.postRun.shift();Q.push(c)}P(Q)}}if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ea();P(R);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();K?moduleRtn=d:moduleRtn=new Promise((a,c)=>{A=a;B=c});
;return moduleRtn}export default OpenEXR;
