async function OpenEXR(moduleArg={}){var moduleRtn;var c=moduleArg,p=!!globalThis.WorkerGlobalScope,aa=import.meta.url,q="",r,t;if(globalThis.window||p){try{q=(new URL(".",aa)).href}catch{}p&&(t=a=>{var d=new XMLHttpRequest;d.open("GET",a,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});r=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var v=console.log.bind(console),w=console.error.bind(console),y,z=!1,A,B,C,D,E,F,G,H,I,J,K=!1;
function L(){var a=M.buffer;c.HEAP8=C=new Int8Array(a);c.HEAP16=E=new Int16Array(a);c.HEAPU8=D=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAP32=F=new Int32Array(a);c.HEAPU32=G=new Uint32Array(a);c.HEAPF32=H=new Float32Array(a);c.HEAPF64=I=new Float64Array(a);J=new BigInt64Array(a);new BigUint64Array(a)}function N(a){c.onAbort?.(a);a="Aborted("+a+")";w(a);z=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");B?.(a);throw a;}var O;
async function ba(a){if(!y)try{var d=await r(a);return new Uint8Array(d)}catch{}if(a==O&&y)a=new Uint8Array(y);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,d){try{var b=await ba(a);return await WebAssembly.instantiate(b,d)}catch(e){w(`failed to asynchronously prepare wasm: ${e}`),N(e)}}
async function da(a){var d=O;if(!y)try{var b=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,a)}catch(e){w(`wasm streaming compile failed: ${e}`),w("falling back to ArrayBuffer instantiation")}return ca(d,a)}
var P=a=>{for(;0<a.length;)a.shift()(c)},Q=[],R=[],ea=()=>{var a=c.preRun.shift();R.push(a)},S=globalThis.TextDecoder&&new TextDecoder,T=(a,d=0,b,e)=>{var f=d;b=f+b;if(e)e=b;else{for(;a[f]&&!(f>=b);)++f;e=f}if(16<e-d&&a.buffer&&S)return S.decode(a.subarray(d,e));for(f="";d<e;)if(b=a[d++],b&128){var h=a[d++]&63;if(192==(b&224))f+=String.fromCharCode((b&31)<<6|h);else{var g=a[d++]&63;b=224==(b&240)?(b&15)<<12|h<<6|g:(b&7)<<18|h<<12|g<<6|a[d++]&63;65536>b?f+=String.fromCharCode(b):(b-=65536,f+=String.fromCharCode(55296|
b>>10,56320|b&1023))}}else f+=String.fromCharCode(b);return f},fa=[null,[],[]],U=(a,d,b)=>{var e=D;if(!(0<b))return 0;var f=d;b=d+b-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(d>=b)break;e[d++]=g}else if(2047>=g){if(d+1>=b)break;e[d++]=192|g>>6;e[d++]=128|g&63}else if(65535>=g){if(d+2>=b)break;e[d++]=224|g>>12;e[d++]=128|g>>6&63;e[d++]=128|g&63}else{if(d+3>=b)break;e[d++]=240|g>>18;e[d++]=128|g>>12&63;e[d++]=128|g>>6&63;e[d++]=128|g&63;h++}}e[d]=0;return d-f},Y=(a,d,b,e)=>{var f=
{string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){for(var m=l=0;m<k.length;++m){var x=k.charCodeAt(m);127>=x?l++:2047>=x?l+=2:55296<=x&&57343>=x?(l+=4,++m):l+=3}l+=1;m=V(l);U(k,m,l);l=m}return l},array:k=>{var l=V(k.length);C.set(k,l);return l}};a=c["_"+a];var h=[],g=0;if(e)for(var n=0;n<e.length;n++){var u=f[b[n]];u?(0===g&&(g=W()),h[n]=u(e[n])):h[n]=e[n]}b=a(...h);return b=function(k){0!==g&&X(g);return"string"===d?k?T(D,k):"":"boolean"===d?!!k:k}(b)};c.print&&(v=c.print);c.printErr&&(w=c.printErr);
c.wasmBinary&&(y=c.wasmBinary);if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.shift()();c.ccall=Y;c.cwrap=(a,d,b,e)=>{var f=!b||b.every(h=>"number"===h||"boolean"===h);return"string"!==d&&f&&!e?c["_"+a]:(...h)=>Y(a,d,b,h,e)};
c.setValue=function(a,d,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":C[a]=d;break;case "i8":C[a]=d;break;case "i16":E[a>>1]=d;break;case "i32":F[a>>2]=d;break;case "i64":J[a>>3]=BigInt(d);break;case "float":H[a>>2]=d;break;case "double":I[a>>3]=d;break;case "*":G[a>>2]=d;break;default:N(`invalid type for setValue: ${b}`)}};
c.getValue=function(a,d="i8"){d.endsWith("*")&&(d="*");switch(d){case "i1":return C[a];case "i8":return C[a];case "i16":return E[a>>1];case "i32":return F[a>>2];case "i64":return J[a>>3];case "float":return H[a>>2];case "double":return I[a>>3];case "*":return G[a>>2];default:N(`invalid type for getValue: ${d}`)}};c.UTF8ToString=(a,d,b)=>a?T(D,a,d,b):"";c.stringToUTF8=(a,d,b)=>U(a,d,b);
var X,V,W,M,ha={k:()=>{},i:()=>{},h:function(){},e:()=>{},c:()=>{},j:a=>{var d=D.length;a>>>=0;if(2147483648<a)return!1;for(var b=1;4>=b;b*=2){var e=d*(1+.2/b);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-M.buffer.byteLength+65535)/65536|0;try{M.grow(e);L();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},b:()=>52,g:function(){return 52},f:function(){return 52},d:function(){return 70},a:(a,d,b,e)=>{for(var f=0,h=0;h<b;h++){var g=G[d>>2],n=G[d+
4>>2];d+=8;for(var u=0;u<n;u++){var k=a,l=D[g+u],m=fa[k];0===l||10===l?((1===k?v:w)(T(m)),m.length=0):m.push(l)}f+=n}G[e>>2]=f;return 0}},Z;
Z=await (async function(){function a(b){b=Z=b.exports;c._exr_wasm_init=b.n;c._exr_wasm_version=b.o;c._exr_wasm_create_write_context=b.p;c._malloc=b.q;c._free=b.r;c._exr_wasm_add_channel=b.s;c._exr_wasm_set_compression=b.t;c._exr_wasm_set_chromaticities=b.u;c._exr_wasm_set_adopt_neutral=b.v;c._exr_wasm_write_pixels=b.w;c._exr_wasm_write_interleaved=b.x;c._exr_wasm_finalize=b.y;c._exr_wasm_get_output_ptr=b.z;c._exr_wasm_get_output_size=b.A;c._exr_wasm_destroy_context=b.B;c._exr_wasm_create_read_context=
b.C;c._exr_wasm_get_dimensions=b.D;c._exr_wasm_get_channel_count=b.E;c._exr_wasm_get_channel_name=b.F;c._exr_wasm_get_channel_pixel_type=b.G;c._exr_wasm_get_compression=b.H;c._exr_wasm_read_pixels=b.I;c._exr_wasm_get_chromaticities=b.J;c._exr_wasm_get_last_error=b.K;c._exr_wasm_clear_error=b.L;c._exr_wasm_get_memory_stats=b.M;X=b.N;V=b.O;W=b.P;M=b.l;L();return Z}var d={a:ha};if(c.instantiateWasm)return new Promise(b=>{c.instantiateWasm(d,(e,f)=>{b(a(e,f))})});O??=c.locateFile?c.locateFile?c.locateFile("openexr.wasm",
q):q+"openexr.wasm":(new URL("openexr.wasm",import.meta.url)).href;return a((await da(d)).instance)}());
(function(){function a(){c.calledRun=!0;if(!z){K=!0;Z.m();A?.(c);c.onRuntimeInitialized?.();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var d=c.postRun.shift();Q.push(d)}P(Q)}}if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)ea();P(R);c.setStatus?(c.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>c.setStatus(""),1);a()},1)):a()})();K?moduleRtn=c:moduleRtn=new Promise((a,d)=>{A=a;B=d});
;return moduleRtn}export default OpenEXR;
